language: node_js
node_js:
    - 7
    - 6

script:
  - npm run codestyle
  - npm run 6to5:client:dev
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false

