language: node_js
node_js:
    - 0.10
    - 0.12
    - iojs

matrix:
  allow_failures:
    - node_js: 'iojs'

before_install:
  - npm install bower -g

script:
  - npm run gulp
  - node start -- --test

notifications:
    email:
        on_success: never
        on_failure: change
