language: node_js
node_js:
    - 5
    - 4
    - 0.12

script:
  - npm codestyle
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false
