language: node_js
node_js:
    - 8
    - 7
    - 6

script:
  - npm run codestyle
  - npm run 6to5:client:dev
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: required

services:
  - docker

deploy:
    provider: script
    script:
        - npm run build
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - npm run docker
    skip_cleanup: true
    on:
        node: '8'
        tags: true
        all_branches: false

