language: node_js
node_js:
  - 15
  - 14

cache:
  npm: false

os:
  - linux
  - os x 

script:
  - npm run lint && npm run build && npm run coverage && npm run report

notifications:
  email:
    on_success: never
    on_failure: change

sudo: required

services:
  - docker

before_deploy:
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | tee $HOME/.docker/config.json
  - sudo service docker start

deploy:
  provider: script
  script: npm run docker-ci
  skip_cleanup: true
  on:
    node: 14
    condition: $TRAVIS_OS_NAME = linux
    tags: true
    all_branches: false
