environment:
  matrix:
  # node.js
  - nodejs_version: "0.12"
  # io.js
  - nodejs_version: "1.0"

install:
  - ps: Install-Product node $env:nodejs_version
   # install modules
  - npm i bower -g
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run yaspeller
  - npm test
